<?php
define("SGPB_MAILCHIMP_MAIN_FILE", 'popup-builder-mailchimp.php');
define("SGPB_MAILCHIMP_ADDON_KEY", 'mailchimp');
define("SGPB_MAILCHIMP_PLUGIN_NAME", 'popup-builder-mailchimp');
define("SGPB_MAILCHIMP_PATH", WP_PLUGIN_DIR."/".SGPB_MAILCHIMP_PLUGIN_NAME);
define("SGPB_MAILCHIMP_URL", plugins_url()."/".SGPB_MAILCHIMP_PLUGIN_NAME);
define("SGPB_MAILCHIMP_CLASSES", SGPB_MAILCHIMP_PATH."/classes/");
define("SGPB_MAILCHIMP_JS", SGPB_MAILCHIMP_PATH."/js/");
define("SGPB_MAILCHIMP_IMG", SGPB_MAILCHIMP_PATH."/images/");
define("SGPB_MAILCHIMP_STYLE", SGPB_MAILCHIMP_PATH."/style/");
define("SGPB_MAILCHIMP_HELPER", SGPB_MAILCHIMP_PATH."/helper/");
define("SGPB_MAILCHIMP_JAVASCRIPT", SGPB_MAILCHIMP_PATH."/javascript/");
define("SGPB_MAILCHIMP_STYLE_URL", SGPB_MAILCHIMP_URL."/style/");
define("SGPB_MAILCHIMP_FILES_PATH", SGPB_MAILCHIMP_PATH."/files");
define("SG_MAILCHIMP_LIST_LIMIT", 200);
define("SG_MAILCHIMP_VERSION", 1.27);